/**
 * Auto-generated by infra/scripts/deploy-uab.ts
 * Do not edit manually.
 */

export const uabAddresses = {
  chainId: 11155111,
  wormholeCore: "0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78" as const,
  wormholeChainId: 2,
  UABSender: "0x872787c0BD1A0C71e6D1be5a144EB044e0CB2069" as const,
  UABReceiver: "0x9eF189f7a263F870Cf80f9A89d1349A6AF7b15cF" as const,
  admin: "0x0A69d334038863Cd4EF9f2c07a22396883fB6AC3" as const,
} as const;

export type UabAddresses = typeof uabAddresses;
