/**
 * Deploy the Universal Announcement Bus (UAB) on Ethereum:
 *   - UABSender   (emits legacy Announcement + publishes the 96-byte payload to Wormhole)
 *   - UABReceiver (verifies incoming VAAs from the Solana emitter, emits CrossChainAnnouncement)
 *
 * The Solana emitter is set later (setExpectedEmitter) once the Solana uab program is deployed.
 *
 * Run:
 *   cd infra && npx hardhat compile && tsx scripts/deploy-uab.ts
 *
 * Env (.env): SEPOLIA_RPC_URL, SEPOLIA_PRIVATE_KEY, optional DEPLOYER_ADDRESS (admin).
 */

import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const FRONTEND_CONTRACTS = path.join(__dirname, "..", "..", "frontend", "src", "contracts");

// Wormhole Core Contract on Ethereum Sepolia + Wormhole chain ids.
const WORMHOLE_CORE_SEPOLIA = "0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78";
const WORMHOLE_CHAIN_ETHEREUM = 2;
const WORMHOLE_CHAIN_SOLANA = 1;
const ZERO32 = "0x" + "00".repeat(32);

type Artifact = { abi: unknown[]; bytecode?: string };

function loadArtifact(contractName: string): Artifact {
  const p = path.join(ARTIFACTS_DIR, `${contractName}.sol`, `${contractName}.json`);
  const artifact = JSON.parse(fs.readFileSync(p, "utf-8")) as Artifact;
  if (!Array.isArray(artifact.abi)) throw new Error(`No ABI in ${p}`);
  return artifact;
}

async function deploy(signer: ethers.Wallet, name: string, nonce: number, args: unknown[] = []): Promise<string> {
  const artifact = loadArtifact(name);
  const factory = new ethers.ContractFactory(artifact.abi as ethers.InterfaceAbi, artifact.bytecode ?? "0x", signer);
  const contract = await factory.deploy(...args, { nonce });
  await contract.waitForDeployment();
  const address = await contract.getAddress();
  console.log(`  ${name} deployed at: ${address}`);
  return address;
}

async function main() {
  const rpcUrl = process.env.SEPOLIA_RPC_URL;
  if (!rpcUrl) throw new Error("Set SEPOLIA_RPC_URL in .env");
  const privateKey = process.env.SEPOLIA_PRIVATE_KEY;
  if (!privateKey?.startsWith("0x") || privateKey.length < 64) throw new Error("Set SEPOLIA_PRIVATE_KEY in .env");

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const signer = new ethers.Wallet(privateKey, provider);
  const deployerAddress = await signer.getAddress();
  const chainId = Number((await provider.getNetwork()).chainId);
  const balance = await provider.getBalance(deployerAddress);
  let nonce = await signer.getNonce("latest");

  console.log(`Deploying UAB on chain ${chainId}`);
  console.log(`Deployer: ${deployerAddress}`);
  console.log(`Balance:  ${ethers.formatEther(balance)} ETH`);
  console.log(`Wormhole: ${WORMHOLE_CORE_SEPOLIA}\n`);

  console.log("Deploying UABSender...");
  const sender = await deploy(signer, "UABSender", nonce++, [WORMHOLE_CORE_SEPOLIA, WORMHOLE_CHAIN_ETHEREUM]);

  const adminAddress = process.env.DEPLOYER_ADDRESS ?? deployerAddress;
  console.log(`\nDeploying UABReceiver (admin: ${adminAddress}; source chain ${WORMHOLE_CHAIN_SOLANA}, emitter TBD)...`);
  const receiver = await deploy(signer, "UABReceiver", nonce++, [
    WORMHOLE_CORE_SEPOLIA,
    adminAddress,
    WORMHOLE_CHAIN_SOLANA,
    ZERO32,
  ]);

  const addresses = {
    chainId,
    wormholeCore: WORMHOLE_CORE_SEPOLIA,
    wormholeChainId: WORMHOLE_CHAIN_ETHEREUM,
    UABSender: sender,
    UABReceiver: receiver,
    admin: adminAddress,
    // The Solana uab emitter (32-byte Wormhole emitter) — set via UABReceiver.setExpectedEmitter
    // and recorded here once the Solana program is deployed.
    solanaEmitterChain: WORMHOLE_CHAIN_SOLANA,
    solanaEmitter: ZERO32,
  };

  fs.mkdirSync(FRONTEND_CONTRACTS, { recursive: true });
  const jsonPath = path.join(FRONTEND_CONTRACTS, "uab-addresses.json");
  fs.writeFileSync(jsonPath, JSON.stringify(addresses, null, 2), "utf-8");
  console.log(`\nWrote ${jsonPath}`);

  const tsContent = `/**
 * Auto-generated by infra/scripts/deploy-uab.ts
 * Do not edit manually.
 */

export const uabAddresses = {
  chainId: ${chainId},
  wormholeCore: "${WORMHOLE_CORE_SEPOLIA}" as const,
  wormholeChainId: ${WORMHOLE_CHAIN_ETHEREUM},
  UABSender: "${sender}" as const,
  UABReceiver: "${receiver}" as const,
  admin: "${adminAddress}" as const,
} as const;

export type UabAddresses = typeof uabAddresses;
`;
  const tsPath = path.join(FRONTEND_CONTRACTS, "uabAddresses.ts");
  fs.writeFileSync(tsPath, tsContent, "utf-8");
  console.log(`Wrote ${tsPath}`);

  const abisDir = path.join(FRONTEND_CONTRACTS, "abis");
  fs.mkdirSync(abisDir, { recursive: true });
  for (const name of ["UABSender", "UABReceiver"]) {
    const artifact = loadArtifact(name);
    fs.writeFileSync(path.join(abisDir, `${name}.json`), JSON.stringify(artifact.abi, null, 2), "utf-8");
    console.log(`Copied ABI: abis/${name}.json`);
  }

  console.log("\nDone. Summary:");
  console.log(JSON.stringify(addresses, null, 2));
  console.log("\nNext:");
  console.log("  1. Deploy the Solana uab program, get its 32-byte emitter PDA.");
  console.log(`  2. UABReceiver.setExpectedEmitter(${WORMHOLE_CHAIN_SOLANA}, <solana emitter>).`);
  console.log("\nVerify with:");
  console.log(`  npx hardhat verify --network sepolia ${sender} ${WORMHOLE_CORE_SEPOLIA} ${WORMHOLE_CHAIN_ETHEREUM}`);
  console.log(
    `  npx hardhat verify --network sepolia ${receiver} ${WORMHOLE_CORE_SEPOLIA} ${adminAddress} ${WORMHOLE_CHAIN_SOLANA} ${ZERO32}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
