/**
 * Deploy the V2 Programmable Stealth Reputation stack:
 *   - Groth16VerifierV2        (4 public signals; vkey == Solana V2 circuit)
 *   - OpaqueSchemaRegistry      (mirror of Solana schema-registry)
 *   - OpaqueAttestationRegistry (mirror of Solana attestation-engine-v2)
 *   - OpaqueReputationVerifierV2 (V2 proof verifier + root/nullifier registry)
 *
 * Writes addresses + ABIs to the frontend so the dashboard can use the V2 PSR system.
 *
 * Run:
 *   cd infra && npx hardhat compile && tsx scripts/deploy-reputation-v2.ts
 *
 * Env (.env): SEPOLIA_RPC_URL, SEPOLIA_PRIVATE_KEY, optional DEPLOYER_ADDRESS (admin).
 */

import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const FRONTEND_CONTRACTS = path.join(__dirname, "..", "..", "frontend", "src", "contracts");

type Artifact = { abi: unknown[]; bytecode?: string };

function loadArtifact(contractName: string): Artifact {
  const p = path.join(ARTIFACTS_DIR, `${contractName}.sol`, `${contractName}.json`);
  const artifact = JSON.parse(fs.readFileSync(p, "utf-8")) as Artifact;
  if (!Array.isArray(artifact.abi)) throw new Error(`No ABI in ${p}`);
  return artifact;
}

async function deploy(
  signer: ethers.Wallet,
  name: string,
  nonce: number,
  args: unknown[] = []
): Promise<string> {
  const artifact = loadArtifact(name);
  const factory = new ethers.ContractFactory(
    artifact.abi as ethers.InterfaceAbi,
    artifact.bytecode ?? "0x",
    signer
  );
  const contract = await factory.deploy(...args, { nonce });
  await contract.waitForDeployment();
  const address = await contract.getAddress();
  console.log(`  ${name} deployed at: ${address}`);
  return address;
}

async function main() {
  const rpcUrl = process.env.SEPOLIA_RPC_URL;
  if (!rpcUrl) throw new Error("Set SEPOLIA_RPC_URL in .env");

  const privateKey = process.env.SEPOLIA_PRIVATE_KEY;
  if (!privateKey?.startsWith("0x") || privateKey.length < 64) {
    throw new Error("Set SEPOLIA_PRIVATE_KEY in .env");
  }

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const signer = new ethers.Wallet(privateKey, provider);
  const deployerAddress = await signer.getAddress();
  const chainId = Number((await provider.getNetwork()).chainId);
  const balance = await provider.getBalance(deployerAddress);
  let nonce = await signer.getNonce("latest");

  console.log(`Deploying V2 PSR stack on chain ${chainId}`);
  console.log(`Deployer: ${deployerAddress}`);
  console.log(`Balance:  ${ethers.formatEther(balance)} ETH`);
  console.log(`Nonce:    ${nonce}\n`);

  console.log("Deploying Groth16VerifierV2...");
  const groth16V2 = await deploy(signer, "Groth16VerifierV2", nonce++);

  console.log("\nDeploying OpaqueSchemaRegistry...");
  const schemaRegistry = await deploy(signer, "OpaqueSchemaRegistry", nonce++);

  console.log("\nDeploying OpaqueAttestationRegistry...");
  const attestationRegistry = await deploy(signer, "OpaqueAttestationRegistry", nonce++, [
    schemaRegistry,
  ]);

  const adminAddress = process.env.DEPLOYER_ADDRESS ?? deployerAddress;
  console.log(`\nDeploying OpaqueReputationVerifierV2 (admin: ${adminAddress})...`);
  const reputationV2 = await deploy(signer, "OpaqueReputationVerifierV2", nonce++, [
    groth16V2,
    adminAddress,
  ]);

  // Write addresses (JSON + TS) to the frontend.
  const addresses = {
    chainId,
    Groth16VerifierV2: groth16V2,
    OpaqueSchemaRegistry: schemaRegistry,
    OpaqueAttestationRegistry: attestationRegistry,
    OpaqueReputationVerifierV2: reputationV2,
    admin: adminAddress,
  };

  fs.mkdirSync(FRONTEND_CONTRACTS, { recursive: true });

  const jsonPath = path.join(FRONTEND_CONTRACTS, "reputation-v2-addresses.json");
  fs.writeFileSync(jsonPath, JSON.stringify(addresses, null, 2), "utf-8");
  console.log(`\nWrote ${jsonPath}`);

  const tsContent = `/**
 * Auto-generated by infra/scripts/deploy-reputation-v2.ts
 * Do not edit manually.
 */

export const reputationV2Addresses = {
  chainId: ${chainId},
  Groth16VerifierV2: "${groth16V2}" as const,
  OpaqueSchemaRegistry: "${schemaRegistry}" as const,
  OpaqueAttestationRegistry: "${attestationRegistry}" as const,
  OpaqueReputationVerifierV2: "${reputationV2}" as const,
  admin: "${adminAddress}" as const,
} as const;

export type ReputationV2Addresses = typeof reputationV2Addresses;
`;
  const tsPath = path.join(FRONTEND_CONTRACTS, "reputationV2Addresses.ts");
  fs.writeFileSync(tsPath, tsContent, "utf-8");
  console.log(`Wrote ${tsPath}`);

  // Copy ABIs.
  const abisDir = path.join(FRONTEND_CONTRACTS, "abis");
  fs.mkdirSync(abisDir, { recursive: true });
  for (const name of [
    "Groth16VerifierV2",
    "OpaqueSchemaRegistry",
    "OpaqueAttestationRegistry",
    "OpaqueReputationVerifierV2",
  ]) {
    const artifact = loadArtifact(name);
    fs.writeFileSync(
      path.join(abisDir, `${name}.json`),
      JSON.stringify(artifact.abi, null, 2),
      "utf-8"
    );
    console.log(`Copied ABI: abis/${name}.json`);
  }

  console.log("\nDone. Summary:");
  console.log(JSON.stringify(addresses, null, 2));
  console.log("\nVerify with:");
  console.log(`  npx hardhat verify --network sepolia ${groth16V2}`);
  console.log(`  npx hardhat verify --network sepolia ${schemaRegistry}`);
  console.log(`  npx hardhat verify --network sepolia ${attestationRegistry} ${schemaRegistry}`);
  console.log(`  npx hardhat verify --network sepolia ${reputationV2} ${groth16V2} ${adminAddress}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
